random_ccm: False
random_gains: False
smoothstep: False
gamma: False
add_noise: False
return_rgb_burst: True
permu_nb: 3
crop_sz_h: 512
crop_sz_w: 640
burst_sz: 9
downsample_factor: 4
random_pixelshift: False
calculate_loss: false

ckpt_path: /mnt/samsung/zheng_data/training_log/checkpoints/dbsr/deeprep_synthetic_mice_9/DeepRepNet_ep0190.pth.tar
dataset_path: /mnt/samsung/zheng_data/datasets/NIRI_to_NIRII
save_path: /mnt/samsung/zheng_data/training_log/viz_results/deeprep_b9_allinone
specify_image_id: -1 # -1
save_results: False
split: val
