add_noise: false
burst_sz: 4
calculate_loss: true
ckpt_path: /home/user/zheng/DBSR/pretrained_networks/best.pth.tar
crop_sz_h: 512
crop_sz_w: 640
dataset_path: /mnt/7T/Data/Medical-Public/NIRII_denoising
downsample_factor: 4
gamma: true
permu_nb: 4
random_ccm: true
random_gains: true
random_pixelshift: false
return_rgb_burst: true
save_path: /mnt/7T/zheng/DBSR_results/loggings/b4_1-4_top5_valset
save_results: true
smoothstep: true
specify_image_id: -1
split: val
