random_ccm: True
random_gains: True
smoothstep: True
gamma: True
add_noise: True
return_rgb_burst: True
permu_nb: 5
crop_sz_h: 512
crop_sz_w: 640
burst_sz: 9
downsample_factor: 4
random_pixelshift: False
calculate_loss: True

ckpt_path: /mnt/samsung/zheng_data/training_log/checkpoints/dbsr/deeprep_synthetic_mice_9/DeepRepNet_ep0199.pth.tar
dataset_path: /mnt/samsung/zheng_data/datasets/NIRI_to_NIRII
save_path: /mnt/samsung/zheng_data/training_log/viz_results/deeprep_b9_mice_traj5_test
specify_image_id: -1 # -1
save_results: True
split: test
