add_noise: false
burst_sz: 16
calculate_loss: False
ckpt_path: /home/user/zheng/DBSR/pretrained_networks/b9_deeprep_best.pth.tar
crop_sz_h: 512
crop_sz_w: 640
dataset_path: /mnt/7T/Data/Medical-Public/NIRII_denoising
downsample_factor: 1
gamma: false
permu_nb: 6
random_ccm: false
random_gains: false
random_pixelshift: false
return_rgb_burst: True
save_path: /mnt/7T/zheng/DBSR_results/loggings/b4_test_20231120
save_results: true
smoothstep: false
specify_image_id: -1
split: test
perform_traditional: True
