random_ccm: True
random_gains: True
smoothstep: True
gamma: True
add_noise: True
return_rgb_burst: True

crop_sz: 384
burst_sz: 8
downsample_factor: 4

ckpt_path: /mnt/data0/zheng/NightCity_1024x512/training_results/checkpoints/dbsr/model-23_synthetic/DBSRNet_ep0100.pth.tar
dataset_path: /mnt/data0/zheng/NightCity_1024x512
trajectory_path: None
save_path: None
use_saved_results: None
specify_trajetory_num: -1
specify_image_id: None
save_results: False
save_pixelShifts: False
split: val