random_ccm: False
random_gains: False
smoothstep: False
gamma: False
add_noise: True
return_rgb_burst: True

crop_sz: [448, 448]
burst_sz: 16
downsample_factor: 4
random_pixelshift: False

ckpt_path: /mnt/samsung/zheng/downloaded_datasets/zheng_ccvl2/training_results/checkpoints/dbsr/visible_train-3_test-2/DBSRNet_ep0100.pth.tar
dataset_path: /mnt/samsung/zheng/downloaded_datasets/zheng_ccvl2/nir_visible
trajectory_path: /home/yutong/zheng/projects/DBSR/util_scripts/traj_files/nir_trajectory.pkl
save_path: /mnt/samsung/zheng/downloaded_datasets/zheng_ccvl2/resultsForJinwen/resultSR_on_USAF_overfitted_2
use_saved_results: None
specify_trajetory_num: 0
specify_image_id: -1 # -1
save_results: True
save_pixelShifts: False
split: test-2
burst_need_downsample: false
