random_ccm: False
random_gains: False
smoothstep: False
gamma: False
add_noise: False
return_rgb_burst: True
permu_nb: 12
crop_sz: 384
burst_sz: 3
downsample_factor: 4
random_pixelshift: False
calculate_loss: True

ckpt_path: /home/yutong/zheng/projects/dbsr_rl/DBSR/pretrained_networks/dbsr_synthetic_default.pth
dataset_path: /mnt/samsung/zheng/downloaded_datasets/zheng_ccvl2/SyntheticDataset
save_path: /mnt/samsung/zheng/downloaded_datasets/zheng_ccvl21/training_log/viz_results/dbsr_burst3_shift12
specify_image_id: -1 # -1
save_results: True
split: val