random_ccm: False
random_gains: False
smoothstep: False
gamma: False
add_noise: False
return_rgb_burst: True
permu_nb: 14
crop_sz: 384
burst_sz: 3
downsample_factor: 4
random_pixelshift: False
calculate_loss: True

ckpt_path: /mnt/samsung/zheng/downloaded_datasets/zheng_ccvl21/training_log/checkpoints/dbsr/burst3_random/best_burst3_random.pth.tar
dataset_path: /mnt/samsung/zheng/downloaded_datasets/zheng_ccvl2/SyntheticDataset
save_path: /mnt/samsung/zheng/downloaded_datasets/zheng_ccvl21/training_log/viz_results/dbsr_burst3_shift14_newweights
specify_image_id: -1 # -1
save_results: True
split: val